travis:
  secure:
    BINSTAR_TOKEN: lh+Z2LGdAHvP9HSXFqKk56c8I/YTOJvMOrN2WYsERuyBN5ZoPo9ZKlQqmQGFLQNfsdgKsWYBAediPtiMVNxbcJBW9fRaWBLLVIT9l7A/MFlU84sVRH3MwiE5UHoL9nxjS6HUBrUT+Q4onZwOZ3JPbNPuqA3aDYoYQVylvlCFwvS5mmp5n+wIcwQ3lAFBrgBkT43OO6D5meURQJkMHUaQVep20VH8PU3lIz0xsVNbPNzfQS9L0QSJYa8UL9nwqERgA3Gxie9CYDUhxCBmJT40FvsHDthtifFhut9LkewWm/N6NtHNvE+7SBJeBKERlkYLyYqQlC2tow79lCFLC2jP9CWw2V2oSA/E4wVM1XiqbY8d+pzgmX1AX02N1SquxrGvFl9UTPHxnwQJ6povjyftKtAvbt+a6IteqG52EBh3/Sk3Eh1S+cO+vd4ys4yrEFODEpd5Nzir6kxSUyCgCeERAb00wPQF6QOOET0SNa5DGgWKSnGZPXY8Kf5xiiyIQ5ggmT48PX6IC6vi33ebR4R2yT/oitKAW+1T8ph+CyE66CFkEGopcVQM29gVIFqoPD8uq7EBo/LfaePWKc2v6AE37Wni0mGtbvcqYDf43grYdaoh3fh2tGvbzZTMFK+YUo1o/OtacfMkLDbiLQqe9YQdseIpciKyRr0tfrrvyUaUSmI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
