travis:
  secure:
    BINSTAR_TOKEN: aJWLlbg1xEQZF+w/GRIsKzpixrqXVL8k6J6ckJfWE21myk1I0QCPp6amdxKqPvWWuZr04g8Y6FHT6u+xjctLWiLL/4SSlzb4gfn8bOZRffFId+vURaFBETz/B3h+MnFYU7F+bi1AXd+UeKYqVRVvX6cgJPF/LpkKjt7PRWzEX5VCt3bX8Brc9ZYpeYDZrfqzC0kj+YAmdVY9pIm3VulY8esY7RkoL6b3l8hA2LoUm/FgBRlKnEQbE+U/ShGpZijZM4zFWJIRorCEmXGLY3vYxQfDO2L4SgdFddty7AH9v8pkpdjBc6mbK65rtygZGOiMYh63GljhVV519hu7ifHjuU4vCx4XKGrEOXb3svadZt5KaEyW4QvdB53EaTSEhnN0eSyq4yl5giPzYmQcWgp8TSd0GewCKvNwnfos10PTj/Rnt/JMl2eK6482YxOPPqbL1ClAzhOk61ATA8hqxXZ0zFJjkz3NSsdpSGJEhRWYsPPTm0gmRkn0W/botxTSUJElflAeMxLoK+BKq+Yr7A9WFv7gNZxGHPw/6vCnqIdtgdbpViUsbN3pCml9ENN90TS/9UXdj6Lmr9d4ShIGbtbAKv3iQrcBqF771lGF228EJbWaAvDEv7UNGTY5itxNp/eZSkvEhu4V5pYHtAJO6IS6Rtd3RPdcBwOmrfQJonSvKRk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
